exports.composersListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="beethoven.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Music Composers</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composers List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Biography</th><th>Birth-Date</th><th>Passing-Date</th><th>Period</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].bio}</td>
                    <td>${slist[i].dataNasc}</td>
                    <td>${slist[i].dataObito}</td>
                    <td>${slist[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.composerFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="beethoven.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Birth Date</label>
                        <input class="w3-input w3-round" type="text" name="bdate"/>
                        <label>Passing Date</label>
                        <input class="w3-input w3-round" type="text" name="pdate"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="period"/>
                    </fieldset>
 
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
`
}

exports.composerFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="beethoven.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                        <label>Birth Date</label>
                        <input class="w3-input w3-round" type="text" name="nascimento" value="${a.dataNasc}"/>
                        <label>Passing Date</label>
                        <input class="w3-input w3-round" type="text" name="morte" value="${a.dataObito}"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                    </fieldset>
                `           

    pagHTML += `
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.composersPeriodPage = function(c, p, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers from ${p}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Composers from ${p}</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Period</th>
                        </tr>
    `;
    c.forEach(composer => {
        pagHTML += `
                <tr>
                    <td>${composer.id}</td>
                    <td>${composer.nome}</td>
                    <td>${composer.dataNasc}</td>
                    <td>${composer.dataObito}</td>
                </tr>
        `;
    });
    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-teal">
                    <address><a href="/">Voltar</a></address>
                </footer>
            </div>
        </body>
    </html>
    `;
    return pagHTML;
}

exports.periodosListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="beethoven.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Music Composers Periods</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1> Period List
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Period</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/periodos/${slist[i].id}">
                            ${slist[i].periodo}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${slist[i].id}">Edit</a>][<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="beethoven.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
 
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `
}

exports.periodoFormEditPage = function(p, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="beethoven.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.periodo}"/>
                    </fieldset>
                `           

    pagHTML += `
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.composerPage = function( c, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Composer: ${c.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="beethoven.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Composer ${c.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${c.nome}</li>
                    <li><b>Bio: </b> ${c.bio}</li>
                    <li><b>Birth Date: </b> ${c.dataNasc}</li>
                    <li><b>Passing Date: </b> ${c.dataObito}</li>
                    <li><b>Period: </b> <a href="/${c.periodo}">${c.periodo}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
</html>
`
    return pagHTML
}

exports.periodoPage = function(p,d){
    var pagHTML = `
    <html>
    <head>
        <title>Period: ${p.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="beethoven.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Period ${p.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${p.periodo}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
</html>
`
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}